import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Layout from '../components/Layout';
import { getProducts } from '../database/connect';
import grünStringer from '../public/1-Green Fitness Stringer.jpg';
import rosa from '../public/2-Pink Water Bottle.jpg';
import grünJogger from '../public/3-Green Joggers.jpg';
import blauJogger from '../public/4-Blue Joggers.jpg';
import weißShirt from '../public/5-White Performance Shirt.jpg';
import grauBag from '../public/6-Grey Bag.jpg';
import heroimage from '../public/heroImage.jpg';

const bodyStyles = css`
  margin-left: 60px;
  margin-right: 60px;
`;
const grid = css`
  display: grid;
  gap: 2rem;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  margin-top: 80px;
`;
const item = css`
  background-color: red;
`;
const item11 = css``;
const item22 = css``;
const item1 = css``;
const item2 = css``;
const item3 = css``;
const item4 = css``;
const item5 = css``;
const item6 = css``;

const row = css``;
const column = css``;
const heroImage = css``;
const heroText = css`
  text-align: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: white;
`;
export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={bodyStyles}>
        <div /* css={heroImage} className="heroImage" */
        /* style={{ width: '100%', height: '100%', position: 'relative' }} */
        >
          <div
            css={css`
              position: relative;
              width: 100%;
              height: 100%;
              margin-top: 40px;
              display: grid;
              justify-content: center;
            `}
          >
            <Image
              src={'/heroImage.jpg'}
              alt=""
              width={400}
              height={400}
              /* fill */
              style={{ objectFit: 'cover', opacity: 0.5 }}
            />
          </div>
          <div css={heroText} className="heroText">
            <h1>I am John Doe</h1>
            <p>And I'm a Photographer</p>
            <button>Hire me</button>
          </div>
        </div>

        <section css={grid}>
          <div css={[item, item1]}>
            <figure>
              <Image src={grünStringer} alt="guy with green muscleshirt" />
            </figure>
            <div>
              <p>Green Fitness Stringer</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>
          <div css={[item, item2]}>
            <figure>
              <Image src={rosa} alt="lady with pink water bottle" />
            </figure>
            <div>
              <p>Pink Water Bottle</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>
          <div css={[item, item3]}>
            <figure>
              <Image src={grünJogger} alt="guy with green Joggers" />
            </figure>
            <div>
              <p>Green Joggers</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>

          <div css={[item, item4]}>
            <figure>
              <Image src={blauJogger} alt="guy with blue joggers" />
            </figure>
            <div>
              <p>Blue Joggers</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>
          <div css={[item, item5]}>
            <figure>
              <Image src={weißShirt} alt="guy with white performance shirt" />
            </figure>

            <div>
              <p>White Performance Shirt</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>
          <div css={[item, item6]}>
            <figure>
              <Image src={grauBag} alt="guy with grey bag" />
            </figure>
            <div>
              <p>Grey Bag</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>
        </section>

        <section css={grid}>
          <div css={[item, item11]}>
            <figure>
              <Image src={grünStringer} alt="guy with green muscleshirt" />
            </figure>
            <div>
              <p>Green Fitness Stringer</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>
          <div css={[item, item22]}>
            <figure>
              <Image src={rosa} alt="lady with pink water bottle" />
            </figure>
            <div>
              <p>Pink Water Bottle</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>
          <div css={[item, item3]}>
            <figure>
              <Image src={grünJogger} alt="guy with green Joggers" />
            </figure>
            <div>
              <p>Green Joggers</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>

          <div css={[item, item4]}>
            <figure>
              <Image src={blauJogger} alt="guy with blue joggers" />
            </figure>
            <div>
              <p>Blue Joggers</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>
          <div css={[item, item5]}>
            <figure>
              <Image src={weißShirt} alt="guy with white performance shirt" />
            </figure>

            <div>
              <p>White Performance Shirt</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>
          <div css={[item, item6]}>
            <figure>
              <Image src={grauBag} alt="guy with grey bag" />
            </figure>
            <div>
              <p>Grey Bag</p>
            </div>
            <div>
              <p>17.95€</p>
            </div>
          </div>
        </section>

        {/* <!-- Basic HTML Form --> */}
        <form action="/send-data-here" method="post">
          <label for="first">First name:</label>
          <input type="text" id="first" name="first" />
          <label for="last">Last name:</label>
          <input type="text" id="last" name="last" />
          <button type="submit">Submit</button>
        </form>

        <section css={row}>
          <div css={column}>
            <Image src={grünStringer} alt="guy with green muscleshirt" />
            <Image src={rosa} alt="lady with pink water bottle" />
            <Image src={grünJogger} alt="guy with green Joggers" />
            <Image src={blauJogger} alt="guy with blue joggers" />
            <Image src={weißShirt} alt="guy with white performance shirt" />
            <Image src={grauBag} alt="guy with grey bag" />
          </div>
        </section>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const products = await getProducts();
  return {
    props: {
      products: products,
    },
  };
}
